log_dir = {
    "tomcat": {
        "types": ["amc", "amcapi", "bmc", "apiCore", "portalCore", "serviceCore", "ssoCore", "api", "apicomet", "apicomet_inner", "cmc", "portal", "service", "sso", "skyforweb", "tomcat"],
        "dir": "/opt/log/tomcat/"
    },
    "nms_webserver": "/opt/log/nms_webserver/",
    "nms_starter": "/opt/log/nms_starter/",
    "nms_adapter": "/opt/log/nms_adapter/",
    "nms_collector": "/opt/log/nms_collector/",
    "nms_bridge26": "/opt/log/nms_bridge26/",
    "nms_bridge48": "/opt/log/nms_bridge48/",
    "nms_bridge_web": "/opt/log/nms_bridge_web/",
    "sm": "/opt/log/sm/",
    "sus": "/opt/log/sus/",
    "sussrv_py": "/opt/log/sussrv_py/",
    "glusterfs": "/usr/local/glusterfs/var/log/glusterfs/",
    "glusterfsd": "/usr/local/glusterfsd/var/log/glusterfs/,/usr/local/glusterfsd/var/log/glusterfs/bricks/",
    "nginx": "/opt/log/nginx/",
    "apigateway": "/opt/log/nginx/",
    "haproxy": "/mnt/log/,/opt/log/haproxy/",
    "media-worker": "/mnt/log/log-local/eqp/,/opt/log/log-local/eqp/mediaresource/",
    "media-master": "/mnt/log/log-local/eqp/,/opt/log/log-local/eqp/mediamaster/",
    "hdupool": "/mnt/log/log-local/eqp/,/opt/log/log-local/eqp/hdupool/",
    "8000aagent": "/mnt/log/log-local/eqp/,/opt/log/log-local/eqp/8000aagent/",
    "apsadp": "/mnt/log/log-local/css/,/opt/log/log-local/css/apsadp",
    "rms": "/mnt/log/log-local/css/,/opt/log/log-local/css/rms/",
    "cdc": "/mnt/log/log-local/css/,/opt/log/log-local/css/cdc/",
    "cds": "/mnt/log/log-local/css/,/opt/log/log-local/css/cds/",
    "css": "/mnt/log/log-local/css/,/opt/log/log-local/css/css/",
    "cmdataproxy": "/mnt/log/log-local/cmu/,/opt/log/log-local/cmu/cmdataproxy/",
    "dss-master": "/mnt/log/log-local/cmu/,/opt/log/log-local/cmu/dssmaster/",
    "dss-worker": "/mnt/log/log-local/cmu/,/opt/log/log-local/cmu/dssworker/",
    "prsworker": "/mnt/log/log-local/cmu/,/opt/log/log-local/cmu/prswk/",
    "cmu": "/mnt/log/log-local/cmu/,/opt/log/log-local/cmu/cmu/",
    "pas": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/pas/",
    "callmanager": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/callmanager/",
    "h323n": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/h323n/",
    "h323nadp": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/h323nadp/",
    "h323s": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/h323s/",
    "h323sadp": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/h323sadp/",
    "mpcadp": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/mpcadp/",
    "ngi": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/ngi/",
    "sipagent": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/sipagent/",
    "sipproxy": "/mnt/log/log/-local/pas/,/opt/log/log-local/pas/sipproxy/",
    "webrtcagent": "/mnt/log/log-local/pas/,/opt/log/log-local/pas/webrtcagent/",
    "protocol": "/mnt/log/log-local/pas/protocol/,/opt/log/log-local/pas/protocol/kdv323adapter_1720/,/opt/log/log-local/pas/protocol/kdv323adapter_1760/,/opt/log/log-local/pas/protocol/kdvsipadapter/,/opt/log/log-local/pas/protocol/kdvsipproxy/,/opt/log/log-local/pas/protocol/RtcAdapterLog/",
    "hduapiagent": "/mnt/log/log-local/hduapiagent/,/opt/log/log-local/hduapiagent/hduapiagent/",
    "aps": "/mnt/log/log-local/aps/,/opt/log/log-local/aps/aps/",
    "wps": "/mnt/log/log-local/wps/,/opt/log/log-local/wps/wps/",
    "restapi": "/mnt/log/log-local/restapi/,/opt/log/log-local/restapi/restapi/",
    "sfuworker": "/mnt/log/log-local/sfuworker/,/opt/log/log-local/sfuworker/sfuworker/,/opt/log/log-local/sfuworker/sfuworker_ops/,/opt/log/log-local/sfuworker/mediasoup/",
    "sfumaster": "/mnt/log/log-local/sfumaster/,/opt/log/log-local/sfumaster/sfumaster/",
    "sfuapiserver": "/mnt/log/log-local/sfuapiserver/,/opt/log/log-local/sfuapiserver/sfuapiserver/",
    "sfuapi": "/mnt/log/log-local/sfuapi/,/opt/log/log-local/sfuapi/",
    "vrspool": "/mnt/log/log-local/vrspool/,/opt/log/log-local/vrspool/vrspool/",
    "keepalived": "/mnt/log/keepalived/,/opt/log/keepalived/Keepalived/",
    "dms": "/opt/log/dms/",
    "graphite": "/opt/log/graphite/",
    "guard": "/opt/log/guard/",
    "kdfs": "/opt/log/kdfs/",
    "modb": "/opt/log/modb/",
    "modbcore": "/opt/log/modbcore/",
    "mo_ejabberd": "/opt/log/mo_ejabberd/",
    "monitor": "/opt/log/monitor/",
    "mysql": "/opt/log/mysql/",
    "pms": "/opt/log/pms/",
    "rabbitmq": "/opt/log/rabbitmq/",
    "radar-server": "/opt/log/radar-server/",
    "redis": "/opt/log/redis/",
    "redis_nms": "/opt/log/redis/",
    "zookeeper": "/opt/log/zookeeper/",
    "syslog-ng": "/opt/log/syslog-ng/",
    "packetbeat": "/opt/log/packetbeat/",
    "metricbeat": "/opt/log/metricbeat/",
    "ejabberd": "/opt/log/mo_ejabberd/",
    "sa": "/mnt/log/log-local/sa/,/opt/log/log-local/sa/sa/",
    "upu": "/opt/log/upu/",
    "upucore": "/opt/log/upucore/",
    "apipush": "/mnt/log/log-local/apipush/,/opt/log/log-local/apipush/",
    "vernemq": "/opt/log/vernemq/",
    "apimqtt": "/mnt/log/log-local/apimqtt/,/opt/log/log-local/apimqtt/",
    "hduapi": "/opt/log/hduapi/",
    "mpu": "/mnt/log/log-local/eqp/,/opt/log/log-local/eqp/mpu/,/opt/log/mediactrl/",
    "tcpdumpmodule": "/opt/log/h323parse/",
    "nds": "/mnt/log/log-local/nds/,/opt/log/log-local/nds/ndslog/",
    "java": "/mnt/log/log-local/nds/,/opt/log/log-local/nds/ndslog/",
    "ns": "/mnt/log/log-local/ns/,/opt/log/log-local/ns/",
    "kdvuaes": "/mnt/log/log-local/kdvuaes/,/opt/log/log-local/kdvuaes/kdvuaes/",
    "system": "/opt/log/log-local/eqp/",
    "docker": "/opt/log/docker/"
}


def GetServerLogDir(serverType):
    path = {
        '/mnt/log/log-local/{}/'.format(serverType),
        '/mnt/log/{}/'.format(serverType),
        '/opt/log/log-local/{}/{}/'.format(serverType, serverType),
        '/opt/log/{}/'.format(serverType)
    }
    if serverType in log_dir['tomcat']['types']:
        path = path.union(set(log_dir['tomcat']['dir'].split(',')))
    elif serverType in log_dir:
        path = path.union(set(log_dir[serverType].split(',')))
    return ','.join(path)
